import type { Metadata } from "next";
import { Cormorant_Garamond } from "next/font/google";
import "./globals.css";

const CormorantFont = Cormorant_Garamond({
  variable: "--font-CormorantGaramond",
  subsets: ["latin"],
  weight: "400", // Add the required weight property
});

export const metadata: Metadata = {
  title: "Fitness",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${CormorantFont.variable} antialiased `}
      >
        {children}
      </body>
    </html >
  );
}
